steps:
# Paso 1: Construir la imagen para xrays-evaluation-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ingeniia-services/xrays-evaluation-service:${SHORT_SHA}', '--file=container-images/xrays_evaluation_service/Dockerfile', '.']

# Paso 2: Enviar (push) la imagen
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ingeniia-services/xrays-evaluation-service:${SHORT_SHA}']

# Paso 3: Desplegar en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'xrays-evaluation-service'
    - '--port=8080'
    - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/ingeniia-services/xrays-evaluation-service:${SHORT_SHA}'
    - '--platform=managed'
    - '--region=us-central1'
    - '--service-account=xrays-evaluation-sa@${PROJECT_ID}.iam.gserviceaccount.com' 
    - '--allow-unauthenticated'
    - '--memory=8Gi' 
    - '--cpu=2'      

options:
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY